package ai.snake.evt;

public enum State {
    KEY_PRESSED_UP, KEY_PRESSED_DOWN, KEY_PRESSED_LEFT, KEY_PRESSED_RIGHT, KEY_INVALID, KEY_PRESSED_SHIFT,
    KEY_PRESSED_TAB, KEY_PRESSED_SPACE, GAME_STATE_PAUSED, GAME_STATE_RUNNING, GAME_STATE_ENDED, FOOD_EATEN, MODE_USER,
    MODE_AI_TEST, MODE_AI_TRAIN, KEY_PRESSED_ARROW_UP, KEY_PRESSED_ARROW_DOWN;
}
