package src.evt;

public enum State {
    MOUSE_PRESSED, MOUSE_RELEASED, KEY_PRESSED_UP, KEY_PRESSED_DOWN, KEY_PRESSED_LEFT, KEY_PRESSED_RIGHT,
    KEY_RELEASED_UP, KEY_RELEASED_DOWN, KEY_RELEASED_LEFT, KEY_RELEASED_RIGHT, KEY_INVALID
}
