package src.evt;

public enum State {
    KEY_PRESSED_UP, KEY_PRESSED_DOWN, KEY_PRESSED_LEFT, KEY_PRESSED_RIGHT, KEY_INVALID, KEY_PRESSED_SHIFT,
    KEY_PRESSED_TAB, KEY_PRESSED_SPACE, GAME_STATE_PAUSED, GAME_STATE_RUNNING, GAME_STATE_ENDED
}
